### ISSUE TITLE
Loading SinGAN

### ISSUE THREAD

**Issue by korenleven** [gfxdisp/mdf#5]
Hey, 
I'm trying to load the SISR weights after cloning the project and I got the following error:

ModuleNotFoundError: No module named 'SinGAN'

May the .pth files are courrupted?

Thanks

**Comment by korenleven** [comment]
?

**Comment by aamir-mustafa** [comment]
Hi,

we have provided the module SinGAN in the repository. You should be able to load it. 

Best
Aamir

**Comment by korenleven** [comment]
Here the directories as cloned
![image](https://user-images.githubusercontent.com/26628527/163774639-45d5519b-7e1b-4db5-bdb5-e0de04dd5d59.png)

But still, the weights curropted
![image](https://user-images.githubusercontent.com/26628527/163774574-37442e31-10da-4419-bb67-43c921a7c1f1.png)

**Comment by korenleven** [comment]
UP

**Comment by aamir-mustafa** [comment]
I have checked all the three checkpoints in the repository. All of them are working fine. 
Could you verify that you have successfully installed all the pip packages in the requirements.txt?

Thanks

**Comment by korenleven** [comment]
Solved.
The problem was that the weights .pth file does not allow to load the file from a different dir.

**Comment by shshojaei** [comment]
> Solved. The problem was that the weights .pth file does not allow to load the file from a different dir.

Hi, Can you explain more how you solve this problem?
