### ISSUE TITLE
ModuleNotFoundError: No module named 'SinGAN'

### ISSUE THREAD

**Issue by Tihetna1891** [gfxdisp/mdf#6]
Hello, I was pretty thrilled to attempt your loss after reading your paper, however, when I tried to adopt the MDF loss by using Denoising.pth  it didn't work, it keeps giving me this issue, could you please tell me how to use your loss in another model?
![image](https://user-images.githubusercontent.com/102287467/170520114-7a61829d-0da1-4acd-881b-978780a40f16.png)

**Comment by aamir-mustafa** [comment]
Hi,
The same issue has been solved here : https://github.com/gfxdisp/mdf/issues/5

Thanks
